environment: 'PRODUCTION'

log_dir: 'log'
default_inputs:
  section_file:
    package: 'data'
    file: 'sections.csv'
output_dirs:
  jsondata: 'output/jsondata'
  keycard: 'output/keycard'
  rosters: 'output/rosters'

# BioRAFT training courses
# Marks primary courses and includes known titles of deprecated courses.
bioraft_training_courses:
  284572:
    title: 'Fire Extinguisher Training'
    primary: True
  2008052:
    title: 'Laser Cutter Safety'
    primary: True
  284587:
    title: 'Hazard Communication'
  1275963:
    title: 'Fire Extinguisher Use, Part 1'
  2051628:
    title: 'Pandemic Safety Officer Training and Awareness'

# CSGold group mapping
# Maps a `door_access` privilege value (room number) to a CSGold patron group number.
csgold_group_mapping:
  base: '154'
  HL A4: '2074'
  HL A5: '791'
  HL A5B: '2034'
  HL A10: '790'
  HL A10A: '789'
  HL A31: '1731'
  HL A4 covid: '2075'
  HL A5 covid: '1657'
  HL A10 covid: '1656'
  HL A10A covid: '1655'
  HL A31 covid: '1732'
  HL A5 summer: '2163'
  HL A10 summer: '2162'
  HL A10A summer: '2161'

# Grouper groups
grouper_groups:
  privileges:
    base_community: 'Apps:IDeATe:Permissions:Base community privileges'
  access:
    laser_cutter_door: 'Apps:IDeATe:Permissions:Laser Cutter:Eligibility:A5B door access'
    skylab_instructor: 'Apps:IDeATe:Access:Logins:Skylab:Instructor access'
    skylab_supplemental: 'Apps:IDeATe:Access:Logins:Skylab:Temporary supplemental access'
    skylab_tech_advisor: 'Apps:IDeATe:Access:Logins:Skylab:Tech Advisor access'
  eligibility:
    'Community role': 'Apps:IDeATe:Permissions:Laser Cutter:Eligibility:Community role'
    'Laser Cutter Safety': 'Apps:IDeATe:Training:BioRAFT:Laser Cutter Safety'
    'Fire Extinguisher Training': 'Apps:IDeATe:Training:BioRAFT:Fire Extinguisher Training'
    'Equipment-specific safety training': 'Apps:IDeATe:Training:Laser Cutter:Equipment-specific safety training'
    'Laser Cutter Login': 'Apps:IDeATe:Access:Logins:Laser Cutter'
    'Positive override': 'Apps:IDeATe:Permissions:Laser Cutter:Overrides Positive'
    'Negative override': 'Apps:IDeATe:Permissions:Laser Cutter:Overrides Negative'
    'Old Fire Extinguisher Part 1': 'Apps:BioRAFT:Courses:Fire_Extinguisher_Use_Part_1'

# MRBS room mapping
# Maps a `room_reservation` privilege value (room number) to a MRBS room ID.
mrbs_room_mapping:
  HL A4: 70
  HL A5: 42
  HL A10: 60
  HL A10A: 56
  HL A31: 69
  HL 106B: 58
  HL 106C: 59
